variable name {}
variable database_version {}
variable region {}
variable deletion_protection {}
variable project {}
variable tier {}
variable ipv4_enabled {}
variable require_ssl {}
variable auth_nw_name {}
variable auth_nw_value {}
variable zone {}
variable sql_user_name {}
variable sql_user_host {}
variable sql_user_password {}