apiVersion: v1
data:
  CHAINLINK_TLS_PORT: "{{.Values.configMap.fm.CHAINLINK_TLS_PORT}}"
  ETH_URL: "{{.Values.configMap.fm.ETH_URL}}"
  ROOT: "{{.Values.configMap.fm.ROOT}}"
  SECURE_COOKIES: "{{.Values.configMap.fm.SECURE_COOKIES}}"
  MINIMUM_CONTRACT_PAYMENT_LINK_JUELS: "{{.Values.configMap.fm.MINIMUM_CONTRACT_PAYMENT_LINK_JUELS}}"
  ALLOW_ORIGINS: "{{.Values.configMap.fm.ALLOW_ORIGINS}}"
  ETH_CHAIN_ID: "{{.Values.configMap.fm.ETH_CHAIN_ID}}"
  ETH_SECONDARY_URLS: "{{.Values.configMap.fm.ETH_SECONDARY_URLS}}"
  DEFAULT_HTTP_ALLOW_UNRESTRICTED_NETWORK_ACCESS: "{{.Values.configMap.fm.DEFAULT_HTTP_ALLOW_UNRESTRICTED_NETWORK_ACCESS}}"

kind: ConfigMap
metadata:
  creationTimestamp: null
  name: {{ .Values.container.configEnv }}
