apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.gcpsmSecretApi }}
  labels:
    type: gcpsm
type: Opaque
stringData:
  secret-access-credentials: |-
    {
      # service account details  
    }